package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/djtouchette/vaulty/internal/framework"
	"github.com/djtouchette/vaulty/internal/policy"
	"github.com/spf13/cobra"
)

func newImportEnvCmd() *cobra.Command {
	var prefix string

	cmd := &cobra.Command{
		Use:   "import-env <file>",
		Short: "Import secrets from a .env file into the vault",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			envPath := args[0]

			f, err := os.Open(envPath)
			if err != nil {
				return fmt.Errorf("opening %s: %w", envPath, err)
			}
			defer f.Close()

			secrets, err := framework.ParseDotenv(f)
			if err != nil {
				return fmt.Errorf("parsing %s: %w", envPath, err)
			}

			if len(secrets) == 0 {
				fmt.Println("No secrets found in file.")
				return nil
			}

			cfg, err := policy.LoadOrDefault("")
			if err != nil {
				return err
			}

			h, err := openVault(cfg.Vault.Path)
			if err != nil {
				return err
			}
			defer h.Vault.Zero()

			count := 0
			for key, val := range secrets {
				storeKey := key
				if prefix != "" {
					storeKey = prefix + key
				}
				h.Vault.Set(storeKey, val)
				count++
			}

			if err := h.Vault.Save(cfg.Vault.Path, h.Passphrase); err != nil {
				return err
			}

			fmt.Printf("Imported %d secrets from %s.\n", count, envPath)
			warnIfNotGitignored(envPath)
			return nil
		},
	}

	cmd.Flags().StringVar(&prefix, "prefix", "", "prefix to add to all key names (e.g. 'APP_')")
	return cmd
}

func newExportEnvCmd() *cobra.Command {
	var (
		outFile string
		reveal  bool
		format  string
	)

	cmd := &cobra.Command{
		Use:   "export-env",
		Short: "Export vault secrets as .env format",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := policy.LoadOrDefault("")
			if err != nil {
				return err
			}

			h, err := openVault(cfg.Vault.Path)
			if err != nil {
				return err
			}
			defer h.Vault.Zero()

			names := h.Vault.List()
			secrets := make(map[string]string, len(names))
			for _, name := range names {
				val, _ := h.Vault.Get(name)
				secrets[name] = val
			}

			if format == "nextjs" {
				return exportNextJS(secrets, outFile, reveal)
			}

			// Default: plain .env
			if outFile != "" {
				f, err := os.Create(outFile)
				if err != nil {
					return fmt.Errorf("creating %s: %w", outFile, err)
				}
				defer f.Close()
				if err := framework.WriteDotenv(f, secrets, reveal); err != nil {
					return err
				}
				fmt.Printf("Exported %d secrets to %s.\n", len(secrets), outFile)
				return nil
			}

			return framework.WriteDotenv(os.Stdout, secrets, reveal)
		},
	}

	cmd.Flags().StringVar(&outFile, "out", "", "output file (default: stdout)")
	cmd.Flags().BoolVar(&reveal, "reveal", false, "show actual values (default: redacted)")
	cmd.Flags().StringVar(&format, "format", "", "output format: nextjs (generates .env.development and .env.production)")
	return cmd
}

func exportNextJS(secrets map[string]string, outDir string, reveal bool) error {
	public, _ := framework.ClassifyNextJSEnv(secrets)
	if len(public) > 0 {
		fmt.Fprintf(os.Stderr, "Warning: %d NEXT_PUBLIC_ variable(s) will be exposed to the browser:\n", len(public))
		for k := range public {
			fmt.Fprintf(os.Stderr, "  - %s\n", k)
		}
	}

	dir := "."
	if outDir != "" {
		dir = outDir
	}

	for _, name := range []string{".env.development", ".env.production"} {
		path := filepath.Join(dir, name)
		f, err := os.Create(path)
		if err != nil {
			return fmt.Errorf("creating %s: %w", path, err)
		}

		if _, err := fmt.Fprintf(f, "# Generated by vaulty export-env --format nextjs\n"); err != nil {
			f.Close()
			return err
		}
		if err := framework.WriteDotenv(f, secrets, reveal); err != nil {
			f.Close()
			return err
		}
		f.Close()
		fmt.Printf("Wrote %s\n", path)
	}

	return nil
}

// warnIfNotGitignored checks whether the given file appears in .gitignore.
func warnIfNotGitignored(path string) {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return
	}
	dir := filepath.Dir(absPath)
	base := filepath.Base(absPath)

	gitignorePath := filepath.Join(dir, ".gitignore")
	f, err := os.Open(gitignorePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: %s may not be in .gitignore — do not commit secret files.\n", path)
		return
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Simple match: exact filename or pattern like *.env
		if line == base || line == path || line == ".env" || line == "*.env" {
			return
		}
	}

	fmt.Fprintf(os.Stderr, "Warning: %s may not be in .gitignore — do not commit secret files.\n", path)
}

