package framework

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

// WriteComposeOverride generates a docker-compose.override.yml fragment with
// environment variables for the given service name.
func WriteComposeOverride(w io.Writer, secrets map[string]string, serviceName string) error {
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if _, err := fmt.Fprintln(w, "# Generated by vaulty export-docker"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "services:"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "  %s:\n", serviceName); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "    environment:"); err != nil {
		return err
	}
	for _, k := range keys {
		if _, err := fmt.Fprintf(w, "      %s: %q\n", k, secrets[k]); err != nil {
			return err
		}
	}
	return nil
}

// WriteSecretFiles writes each secret as a separate file under dir/<name>.
// This follows the Docker secrets file convention where each secret is a
// plain file that gets mounted into the container.
func WriteSecretFiles(dir string, secrets map[string]string) error {
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("creating secrets directory %s: %w", dir, err)
	}

	for name, value := range secrets {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(value), 0600); err != nil {
			return fmt.Errorf("writing secret file %s: %w", name, err)
		}
	}
	return nil
}

// composeFile is a minimal representation for parsing docker-compose environment sections.
type composeFile struct {
	Services map[string]composeService `yaml:"services"`
}

type composeService struct {
	Environment yaml.Node `yaml:"environment"`
}

// ParseComposeEnv extracts environment variables from a docker-compose.yml file.
// It supports both mapping syntax (KEY: value) and list syntax (- KEY=value).
func ParseComposeEnv(data []byte) (map[string]string, error) {
	var cf composeFile
	if err := yaml.Unmarshal(data, &cf); err != nil {
		return nil, fmt.Errorf("parsing docker-compose.yml: %w", err)
	}

	result := make(map[string]string)

	for _, svc := range cf.Services {
		node := svc.Environment

		switch node.Kind {
		case yaml.MappingNode:
			// KEY: value pairs
			for i := 0; i+1 < len(node.Content); i += 2 {
				key := node.Content[i].Value
				val := node.Content[i+1].Value
				result[key] = val
			}
		case yaml.SequenceNode:
			// - KEY=value items
			for _, item := range node.Content {
				k, v, _ := splitEnvVar(item.Value)
				if k != "" {
					result[k] = v
				}
			}
		}
	}

	return result, nil
}

func splitEnvVar(s string) (key, value string, ok bool) {
	idx := indexOf(s, '=')
	if idx < 0 {
		return s, "", false
	}
	return s[:idx], s[idx+1:], true
}

func indexOf(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
